config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "users#welcome"

  get "users",            to: redirect("signup")
  get "signin",           to: "sessions#new"
  get "signout",          to: "sessions#destroy"
  get "signup",           to: "users#new"
  get "confirmation",     to: "users#confirmation"
  get "welcome",          to: "users#welcome"

  resources :users, only: %w(show new create update) do
    member do
      get "profile", to: "users#edit"
    end
  end

  resources :sessions, only: %w(new create destroy)
  resources :plantcares
  resources :waterings, only: %w(new create destroy index)
  resources :watering_schedules, except: %w(show)
  resources :board_connections, only: %w(index)
end

app/models/plantcare_api/watering_schedule.rb
# frozen_string_literal: true

module PlantcareApi
  class WateringSchedule < PlantcareApi::Base
    attributes :starts_on,
               :ends_on,
               :status,
               :duration_unit,
               :duration_amount,
               :frequency_unit,
               :frequency_amount,
               :plantcare_id

    DURATION_UNITS = [
      DURATION_IN_SECONDS = "seconds",
      DURATION_IN_MINUTES = "minutes"
    ].freeze

    FREQUENCY_UNITS = [
      FREQUENCY_HOURS = "hours",
      FREQUENCY_DAYS = "days"
    ].freeze
  end
end

app/models/wtever_api/watering_schedule.rb
# frozen_string_literal: true

module WteverApi
  class WateringSchedule < WteverApi::Base
    attributes :starts_on,
               :ends_on,
               :status,
               :duration_unit,
               :duration_amount,
               :frequency_unit,
               :frequency_amount,
               :plantcare_id

    DURATION_UNITS = [
      DURATION_IN_SECONDS = "seconds",
      DURATION_IN_MINUTES = "minutes"
    ].freeze

    FREQUENCY_UNITS = [
      FREQUENCY_HOURS = "hours",
      FREQUENCY_DAYS = "days"
    ].freeze
  end
end

app/controllers/watering_schedules_controller.rb
# frozen_string_literal: true

class WateringSchedulesController < ApplicationController
  def new
    @watering_schedule = PlantcareApi::WateringSchedule.new(plantcare_id: params[:plantcare_id])
  end

  def create
    watering_schedule = PlantcareApi::WateringSchedule.new(watering_schedule_params)

    if watering_schedule.save
      flash[:notice] = I18n.t("watering_schedules.create.sucessfully")
    else
      flash[:error] = to_flash(watering_schedule.response_errors)
    end

    respond_to do |format|
      format.js { render :create }
    end
  end

  def edit
    @watering_schedule = PlantcareApi::WateringSchedule.find(params[:id])
  end

  def update
    watering_schedule = PlantcareApi::WateringSchedule.new(watering_schedule_params)

    if watering_schedule.save
      flash[:notice] = I18n.t("watering_schedules.update.sucessfully")
    else
      flash[:error] = to_flash(@watering_schedule.response_errors)
    end

    respond_to do |format|
      format.js { render :update }
    end
  end

  def destroy
    watering_schedule = PlantcareApi::WateringSchedule.find(params[:id])

    if watering_schedule.destroy
      flash[:notice] = I18n.t("watering_schedules.destroy.sucessfully")
    else
      flash[:error] = to_flash(watering_schedule.response_errors)
    end

    redirect_to plantcares_path
  end

  private

  def watering_schedule_params
    params
      .require(:plantcare_api_watering_schedule)
      .permit(
        :id,
        :plantcare_id,
        :starts_on,
        :ends_on,
        :status,
        :duration_unit,
        :duration_amount,
        :frequency_unit,
        :frequency_amount
      )
  end

  def watering_schedule
    @watering_schedule ||= PlantcareApi::WateringSchedule.find(params[:id])
  end
end

app/views/watering_schedules/_edit.haml
= modal_for("edit_watering_schedule", nil, { footer: false }) do
  - capture_haml do
    = form_for @watering_schedule, url: watering_schedule_path(@watering_schedule), method: :put, remote: true do |f|
      = f.hidden_field :id
      = render partial: "form", locals: { f: f, title: I18n.t("watering_schedules.edit.title") }

app/views/watering_schedules/_form.haml
.plantcare-fields-dark.watering-schedule-panel
  .watering-schedule-left-panel.vline-middle
    .mr-2.ml-2.font-color
      .text-center
        = image_tag "schedule.png", width: "65%"
      %h1.weight-2=title
      %h5.weight-2= I18n.t("watering_schedules.new.explaining")

  .watering-schedule-right-panel.vline-middle
    = f.hidden_field :plantcare_id
    .flex
      = f.text_field :starts_on, class: "form-control datepicker flex-inline", placeholder: I18n.t("watering_schedules.plantcare_api.attributes.starts_on")
      = f.text_field :ends_on, class: "form-control datepicker flex-inline", placeholder: I18n.t("watering_schedules.plantcare_api.attributes.ends_on")

    .flex
      = f.number_field :duration_amount, class: "form-control", placeholder: I18n.t("watering_schedules.plantcare_api.attributes.duration_amount")
      = f.select :duration_unit, PlantcareApi::WateringSchedule::DURATION_UNITS, { prompt: true }, { class: "form-control" }

    .flex
      = f.number_field :frequency_amount, class: "form-control", placeholder: I18n.t("watering_schedules.plantcare_api.attributes.frequency_amount")
      = f.select :frequency_unit, PlantcareApi::WateringSchedule::FREQUENCY_UNITS, { prompt: true }, { class: "form-control" }

    - buttons_class = @watering_schedule.id.present? ? "col-sm-4" : "col-sm-6"
    .mt-4.pt-2.text-right
      .row
        .col-xs-12{ class: buttons_class }
          .form-group
            = submit_tag I18n.t('buttons.submit'), { class: "custom-btn custom-btn-active btn-block custom-btn-inline" }

        .col-xs-12{ class: buttons_class }
          .form-group
            = link_to I18n.t('buttons.cancel'), '#', class: "custom-btn custom-btn-danger btn-block custom-btn-inline", data: { dismiss: "modal" }

        - if @watering_schedule.id.present?
          .col-xs-12{ class: buttons_class }
            .form-group
              = link_to I18n.t('buttons.remove'), watering_schedule_path(@watering_schedule), method: :delete,
                class: "custom-btn custom-btn-danger-secondary btn-block custom-btn-inline",data: { confirm: I18n.t("confirmation") }

app/views/watering_schedules/_new.haml
= modal_for("new_watering_schedule", nil, { footer: false }) do
  - capture_haml do
    = form_for @watering_schedule, url: { controller: "watering_schedules", action: "create" }, method: :post, remote: true do |f|
      = render partial: "form", locals: { f: f, title: I18n.t("watering_schedules.new.title") }

app/views/watering_schedules/create.js.erb
<% if flash[:error].present? %>
  $.growl.error({ message: '<%= raw flash[:error] %>', duration: 10000, title: 'Plantcare says:' });
<% else %>
  $.growl.notice({ message: '<%= raw flash[:notice] %>', duration: 10000, title: 'Plantcare says:' });
  $("#new_watering_schedule").modal('hide');
  window.location.replace("<%= plantcares_path %>");
<% end %>

app/views/watering_schedules/edit.js.erb
$("#edit_watering_schedule_modal").html("<%= j render 'watering_schedules/edit' %>")
$("#edit_watering_schedule").modal();
datepickerControl();

app/views/watering_schedules/new.js.erb
$("#new_watering_schedule_modal").html("<%= j render 'watering_schedules/new' %>")
$("#new_watering_schedule").modal();
datepickerControl();

app/views/watering_schedules/update.js.erb
<% if flash[:error].present? %>
  $.growl.error({ message: '<%= raw flash[:error] %>', duration: 10000, title: 'Plantcare says:' });
<% else %>
  $.growl.notice({ message: '<%= raw flash[:notice] %>', duration: 10000, title: 'Plantcare says:' });
  $("#edit_watering_schedule").modal('hide')
  window.location.replace("<%= plantcares_path %>");
<% end %>