config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "users#welcome"

  get "users",            to: redirect("signup")
  get "signin",           to: "sessions#new"
  get "signout",          to: "sessions#destroy"
  get "signup",           to: "users#new"
  get "confirmation",     to: "users#confirmation"
  get "welcome",          to: "users#welcome"

  resources :users, only: %w(show new create update) do
    member do
      get "profile", to: "users#edit"
    end
  end

  resources :sessions, only: %w(new create destroy)
  resources :plantcares
  resources :waterings, only: %w(new create destroy index)
  resources :watering_schedules, except: %w(show)
  resources :board_connections, only: %w(index)
end

app/models/plantcare_api/user.rb
# frozen_string_literal: true

module PlantcareApi
  class User < PlantcareApi::Base
    attributes :first_name, :last_name, :email, :country_code,
               :timezone, :lang, :password_confirmation, :password, :api_token, :last_healthy_checks

    custom_get :signin

    def board_connections
      return [] if last_healthy_checks.blank?

      last_healthy_checks
    end

    def last_board_connection
      return nil if board_connections.blank?

      board_connections.first
    end
  end
end

app/models/wtever_api/user.rb
# frozen_string_literal: true

module WteverApi
  class User < WteverApi::Base
    attributes :first_name, :last_name, :email, :country_code,
               :timezone, :lang, :password_confirmation, :password, :api_token, :last_healthy_checks

    custom_get :signin

    def board_connections
      return [] if last_healthy_checks.blank?

      last_healthy_checks
    end

    def last_board_connection
      return nil if board_connections.blank?

      board_connections.first
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  skip_before_action :authenticator, only: %w(welcome new create confirmation)
  before_action      :set_user,      only: %w(edit)

  def welcome
    redirect_to plantcares_path if logged?
  end

  def show
  end

  def new
    @user = PlantcareApi::User.new
  end

  def create
    @user              = PlantcareApi::User.new(user_params)
    @user.wtever_token = @user.client_name = "plantcare"

    if @user.save
      redirect_to confirmation_path
    else
      flash[:error] = to_flash(@user.response_errors)

      respond_to do |format|
        format.js   { render :new and return }
        format.html { render :new and return }
      end
    end
  end

  def edit
  end

  def confirmation
  end

  def update
    @user = PlantcareApi::User.new(user_params)

    if @user.save
      flash[:notice] = I18n.t("users.update.sucessfully")
      session[:lang] = @user.lang

      redirect_to profile_user_path(@user) and return
    else
      flash[:error] = to_flash(@user.response_errors)

      render "edit" and return
    end
  end

  private

  def user_params
    params.require(:plantcare_api_user).permit(
      :first_name,
      :last_name,
      :email,
      :password,
      :password_confirmation,
      :country_code,
      :timezone,
      :lang
    ).tap do |permitted_params|
      permitted_params[:id] = params[:id] if params[:id].present?
    end.to_h
  end

  def set_user
    @user = PlantcareApi::User.find(params[:id]) if params[:id].present?
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/users/_basic_form_fields.haml
= f.hidden_field :id if f.object.id.present?

.form-group
  = f.text_field :first_name, class: 'form-control', placeholder: I18n.t('users.plantcare_api.attributes.first_name')
.form-group
  = f.text_field :last_name, class: 'form-control', placeholder: I18n.t('users.plantcare_api.attributes.last_name')
.form-group
  = f.email_field :email, class: 'form-control', placeholder: I18n.t('users.plantcare_api.attributes.email')
.form-group
  = f.password_field :password, class: 'form-control', placeholder: I18n.t('users.plantcare_api.attributes.password')
.form-group
  = f.password_field :password_confirmation, class: 'form-control', placeholder: I18n.t('users.plantcare_api.attributes.password_confirmation')

app/views/users/_extended_form_fields.haml
.form-group
  = f.select :country_code, countries_collection, { prompt: true }, { class: "form-control" }
.form-group
  = f.select :timezone, timezones_collection, { prompt: true }, { class: "form-control" }
.form-group
  = f.select :lang, lang_collection, { prompt: true }, { class: "form-control" }

app/views/users/_features.haml
.row
  .col-xs-12.col-sm-12.col-md-12.col-lg-10.col-xl-8.pb-4
    .flex.align-center.p-2
      .flex.flex-direction-column
        %h4.weight-2= I18n.t("users.welcome.features.feature-1.description").html_safe

    .flex.align-center.pt-2.pb-2.details
      .flex.flex-direction-column
        %h4.bigger-2.weight-3= I18n.t("users.welcome.features.feature-2.title")
        %h4.weight-2= I18n.t("users.welcome.features.feature-2.description").html_safe

    .flex.align-center.pt-2.pb-2.details
      .flex.flex-direction-column
        %h4.bigger-2.weight-3= I18n.t("users.welcome.features.feature-3.title")
        %h4.weight-2= I18n.t("users.welcome.features.feature-3.description").html_safe

    .flex.align-center.pt-2.pb-2.details
      .flex.flex-direction-column
        %h4.bigger-2.weight-3= I18n.t("users.welcome.features.feature-4.title")
        %h4.weight-2= I18n.t("users.welcome.features.feature-4.description").html_safe

.row.full-width
  .col-xs-12.col-sm-6.col-md-4.col-md-offset-1.pt-4
    = link_to t('users.new.title'), signup_path, class: "custom-btn custom-btn-tertiary btn-block"
  .col-xs-12.col-sm-6.col-md-4.pt-4
    = link_to t('buttons.back'), '#intro', class: "custom-btn custom-btn-secondary btn-block rf"

app/views/users/_signup.html.haml
- remote ||= false

= form_for @user, url: { controller:'users', action:'create' }, method: :post, remote: remote do |f|
  = render partial: 'users/basic_form_fields', locals: { f: f }
  = render 'shared/form/submit', f: f, submit_class: 'custom-btn-primary', remote: remote

app/views/users/confirmation.haml
.form.content.vline-middle.flex.flex-direction-column.flex-justify-center.align-center.pb-4
  = render partial: 'shared/title', locals: { title: I18n.t('users.confirmation.title'), subtitle: I18n.t('users.confirmation.subtitle', signin_link: signin_path) }

app/views/users/edit.haml
.form.content.vline-top.flex.flex-direction-column.flex-justify-center.align-center.pb-4
  .row.full-width
    .col-xs-12.col-sm-8.col-sm-offset-2.col-md-8.col-md-offset-2.p-3
      .font-color
        = render partial: 'shared/title', locals: { title: I18n.t('users.edit.title'), subtitle: I18n.t('users.edit.subtitle'), dark: true }

      = form_for @user, url: user_path(@user), method: :put do |f|
        .row.plantcare-fields
          .col-xs-12.col-md-6.text-center
            = render partial: 'users/basic_form_fields',    locals: { f: f }

          .col-xs-12.col-md-6.text-center
            = render partial: 'users/extended_form_fields', locals: { f: f }

        .pt-2
          = render 'shared/form/submit', f: f

app/views/users/new.html.haml
- content_for :header do
  .row
    .col-xs-12.col-sm-4.col-md-4.col-md-offset-1
      %h3.plantcare-icon.mb-3.mt-2
        = link_to root_path do
          = image_tag "logo.png", height: 65

.flex.flex.flex-direction-column.align-center.pb-2.visible-xs
  = flex_image_div image_url: "signup-#{current_user ? current_user.lang : I18n.default_locale}.png", mobile: true
  = flex_panel_div mobile: true, classes: "flex-direction-column" do
    = render partial: 'shared/title', locals: { title: I18n.t('users.new.title'), subtitle: I18n.t('users.new.subtitle') }
    .row.full-width
      .col-xs-12.col-sm-10.col-sm-offset-1.col-md-8.col-md-offset-2
        = render partial: 'users/signup'
    .row.full-width
      .col-xs-12.text-center.primary-color
        = raw I18n.t('users.new.have_account', signup_link: signup_path)

.flex.align-center.pt-2.pb-2.hidden-xs
  = flex_panel_div classes: "flex-direction-column" do
    = render partial: 'shared/title', locals: { title: I18n.t('users.new.title'), subtitle: I18n.t('users.new.subtitle') }
    .row.full-width
      .col-xs-12.col-sm-10.col-sm-offset-1.col-md-8.col-md-offset-2
        = render partial: 'users/signup'
    .row.full-width
      .col-xs-12.text-center.primary-color
        = raw I18n.t('users.new.have_account', signup_link: signup_path)
  = flex_image_div image_url: "signup-#{current_user ? current_user.lang : I18n.default_locale}.png"

= modal_for('signin_modal', I18n.t("sessions.new.subtitle").humanize, { footer: false }) do
  - capture_haml do
    .plantcare-fields-dark
      = render partial: 'sessions/signin', locals: { remote: true }

app/views/users/new.js.erb
<% if flash[:error].present? %>
  $.growl.error({ message: '<%= raw flash[:error] %>', duration: 10000, title: 'Plantcare says:' });
<% end %>

app/views/users/welcome.html.haml
- content_for :header do
  .row
    .col-xs-12.col-sm-4.col-md-4.col-md-offset-1
      %h3.plantcare-icon.mb-3.mt-2
        = link_to root_path do
          = image_tag "logo.png", height: 65

%div{id: "intro"}
  .intro.flex.flex.flex-direction-column.align-center.pb-2.visible-xs
    = flex_image_div image_url: "home.png", mobile: true
    = flex_panel_div mobile: true, classes: "flex-direction-column" do
      = render partial: 'shared/title',
              locals: { title: I18n.t('users.welcome.title'), subtitle: I18n.t('users.welcome.explanation') }
      .full-width.p-2.pt-4
        = link_to t('users.welcome.need_more'), '#features', class: "custom-btn custom-btn-secondary btn-block rf"
        = link_to t('sessions.new.title'), signin_path, class: "custom-btn custom-btn-primary btn-block"
        = link_to t('users.new.title'), signup_path, class: "custom-btn custom-btn-primary custom-btn-active btn-block"

  .intro.flex.align-center.pt-2.pb-2.hidden-xs
    = flex_panel_div classes: "flex-direction-column" do
      = render partial: 'shared/title',
                locals: { title: I18n.t('users.welcome.title'), subtitle: I18n.t('users.welcome.explanation') }
      .full-width.p-2.pt-4{ style: 'width: 40%' }
        = link_to t('users.welcome.need_more'), '#features', class: "custom-btn custom-btn-secondary btn-block rf"
        = link_to t('sessions.new.title'), signin_path, class: "custom-btn custom-btn-primary btn-block"
        = link_to t('users.new.title'), signup_path, class: "custom-btn custom-btn-primary custom-btn-active btn-block"


    = flex_image_div image_url: "home.png"


%div{id: "features"}
  .features.flex.align-center.pt-2.pb-2.hidden-xs
    = flex_image_div image_url: "features.png"
    = flex_panel_div classes: "flex-direction-column" do
      = render partial: 'shared/title', locals: { title: I18n.t('users.welcome.features.title'), classes: "text-left full-width" }
      .full-width
        = render partial: "features"

  .features.flex.align-center.pt-2.pb-2.visible-xs
    = flex_image_div image_url: "features.png", mobile: true
    = flex_panel_div classes: "flex-direction-column", mobile: true do
      = render partial: 'shared/title', locals: { title: I18n.t('users.welcome.features.title') }
      .full-width
        = render partial: "features"