config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "users#welcome"

  get "users",            to: redirect("signup")
  get "signin",           to: "sessions#new"
  get "signout",          to: "sessions#destroy"
  get "signup",           to: "users#new"
  get "confirmation",     to: "users#confirmation"
  get "welcome",          to: "users#welcome"

  resources :users, only: %w(show new create update) do
    member do
      get "profile", to: "users#edit"
    end
  end

  resources :sessions, only: %w(new create destroy)
  resources :plantcares
  resources :waterings, only: %w(new create destroy index)
  resources :watering_schedules, except: %w(show)
  resources :board_connections, only: %w(index)
end

app/views/shared/_footer.html.haml
%ul
  %li
    Plantcare
  %li
    2017 @ lbautista

app/views/shared/_header.html.haml
%nav.navbar.navbar-default
  - if content_for?(:header)
    = yield(:header)
  - else
    .container
      / Brand and toggle get grouped for better mobile display
      .navbar-header
        %button.navbar-toggle.pt-3.collapsed{"aria-expanded" => "false", "data-target" => "#plantcare-navbar", "data-toggle" => "collapse", "type" => "button"}
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        .navbar-brand
          %h2.plantcare-icon.m-0
            = link_to root_path do
              = image_tag "logo.png", height: 65
      #plantcare-navbar.collapse.navbar-collapse
        - if logged?
          = render partial: 'shared/user_actions'

app/views/shared/_not_found.haml
- title    ||= ''
- subtitle ||= ''
- dark     ||= false

.title{ class: "#{'dark' if dark}" }
  .row
    .col-xs-12.col-md-6.col-md-offset-3.text-center
      - if title.present?
        %h3= raw title

      - if subtitle.present?
        %h4.mt-0.mb-3= raw subtitle

app/views/shared/_spinner.haml
.loading-overlay.hidden
  .content.vline-middle
    .spinner.sk-three-bounce
      .sk-child.sk-bounce1
      .sk-child.sk-bounce2
      .sk-child.sk-bounce3

app/views/shared/_title.html.haml
- title    ||= ''
- subtitle ||= ''
- dark ||= false
- classes ||= "text-center"

.title.p-2.third-color.full-width{ class: classes }
  - if title.present?
    %h1.biggest.mb-3{ class: "#{dark ? "font-color" : "" }" }= raw title

  - if subtitle.present?
    .hidden-xs
      .row
        .col-xs-12.col-md-8.col-md-offset-2
          %h4.bigger-2.mt-1.weight-1{ class: "#{dark ? "font-color" : "" }" }= raw subtitle
    .visible-xs
      .row
        .col-xs-12.col-md-8.col-md-offset-2
          %h3.general-font.mt-1.weight-1{ class: "#{dark ? "font-color" : "" }" }= raw subtitle

app/views/shared/_uploader.haml
- multiple ||= false
/ The table listing the files available for upload/download
%table.table.text-center
  %tbody.files{"data-target" => "#modal-gallery", "data-toggle" => "modal-gallery"}
/ The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload
.form-group
  .row.fileupload-buttonbar
    .col-xs-12.col-sm-4
      / The fileinput-button span is used to style the file input field as button
      %span.custom-btn.custom-btn-primary.btn-block.fileinput-button
        %span= I18n.t('buttons.add')
        = f.file_field uploader_name, multiple: multiple

    .col-xs-12.col-sm-4
      = submit_tag I18n.t('buttons.submit'), class: 'custom-btn custom-btn-primary btn-block start'

    .col-xs-12.col-sm-4
      = button_tag I18n.t('buttons.cancel'), type: 'reset', class: 'custom-btn custom-btn-danger btn-block cancel'
/ The loading indicator is shown during image processing
.fileupload-loading
%br/


:javascript  
  $(function () {
      // Initialize the jQuery File Upload widget:
      $fileuploader = $('\##{form_id}');
      $fileuploader.fileupload();
      //
      // Load existing files:
      $.getJSON($fileuploader.prop('action'), function (files) {
        var fu = $fileuploader.data('blueimpFileupload'),
          template;
        fu._adjustMaxNumberOfFiles(-files.length);
        console.log(files);
        template = fu._renderDownload(files)
          .appendTo($fileuploader.find('.files'));
        // Force reflow:
        fu._reflow = fu._transition && template.length &&
          template[0].offsetWidth;
        template.addClass('in');
        $('#loading').remove();
      });
  });

:plain
  <script id="template-upload" type="text/x-tmpl">
    {% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-upload fade">
      <td class="preview"><span class="fade"></span></td>
      <td class="name"><span class="cut-text-1">{%=file.name%}</span></td>
      <td class="size"><span class="cut-text-1">{%=o.formatFileSize(file.size)%}</span></td>
      {% if (file.error) { %}
      <td class="error" colspan="2"><span class="label label-important">{%=locale.fileupload.error%}</span> {%=locale.fileupload.errors[file.error] || file.error%}</td>
      {% } else if (o.files.valid && !i) { %}
      <td>
        <div class="progress progress-success progress-striped active"><div class="bar" style="width:0%;"></div></div>
      </td>
      <td class="start">{% if (!o.options.autoUpload) { %}
        <button class="btn btn-primary">
          <i class="icon-upload icon-white"></i>
          <span>{%=locale.fileupload.start%}</span>
        </button>
        {% } %}</td>
      {% } else { %}
      <td colspan="2"></td>
      {% } %}
      <td class="cancel">{% if (!i) { %}
        <button class="custom-btn-danger custom-btn">
          <i class="icon-ban-circle icon-white"></i>
          <span><%= I18n.t('buttons.cancel') %></span>
        </button>
        {% } %}</td>
    </tr>
    {% } %}
  </script>
  <!-- The template to display files available for download -->
  <script id="template-download" type="text/x-tmpl">
    {% for (var i=0, file; file=o.files[i]; i++) { %}
      <tr class="template-download fade">
        {% if (file.error) { %}
          <td></td>
          <td class="name"><span>{%=file.name%}</span></td>
          <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
          <td class="error" colspan="2"><span class="label label-important">{%=locale.fileupload.error%}</span> {%=locale.fileupload.errors[file.error] || file.error%}</td>
          {% } else { %}
          <td class="preview">{% if (file.thumbnail_url) { %}
            <a href="{%=file.url%}" title="{%=file.name%}" rel="gallery" download="{%=file.name%}"><img src="{%=file.thumbnail_url%}"></a>
            {% } %}</td>
          <td class="name">
            <a href="{%=file.url%}" title="{%=file.name%}" rel="{%=file.thumbnail_url&&'gallery'%}" download="{%=file.name%}">{%=file.name%}</a>
          </td>
          <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
          <td colspan="2"></td>
          {% } %}
        <td class="delete">
          <button class="btn btn-danger" data-type="{%=file.delete_type%}" data-url="{%=file.delete_url%}">
            <i class="icon-trash icon-white"></i>
            <span>{%=locale.fileupload.destroy%}</span>
          </button>
          <input type="checkbox" name="delete" value="1">
        </td>
      </tr>
      {% } %}
  </script>

app/views/shared/_user_actions.haml
- @board_connection_at = current_user.last_board_connection

%ul.nav.navbar-nav.navbar-right
  %li.vline-middle
    = link_to profile_user_path(current_user), title: I18n.t('menu.profile_explanation') do
      = svg_icon_tag("plant-icon", { classes: "icon pr-1 svg-general-color vline-middle" })
      %h5.m-0.third-color.vline-middle.inline-block.weight-2
        = [current_user.first_name, current_user.last_name].join(" ")

  %li.vline-middle
    = link_to signout_path do
      = svg_icon_tag("logout-icon", { classes: "icon pr-1 svg-general-color vline-middle" })
      %h5.m-0.third-color.vline-middle.inline-block.weight-2
        = I18n.t('menu.sign_out')

app/views/shared/_user_profile.haml
- @board_connection_at = current_user.last_board_connection

%ul.nav.navbar-nav.navbar-right
  %li.vline-middle
    = link_to profile_user_path(current_user),
      'data-toggle' => 'tooltip', 'data-placement' => 'bottom', 'title' => I18n.t('menu.profile_explanation') do
      = fa_icon 'fal fa-seedling opposite-color pr-1 bigger-2 vline-middle'
      %h5.m-0.opposite-color.vline-middle.inline-block.weight-2
        = current_user.first_name
  %li.vline-middle
    .block.p-3{ 'data-toggle' => 'tooltip', 'data-placement' => 'bottom', 'title' => I18n.t('menu.status_explanation', board_connection_at: (@board_connection_at.present? ? I18n.localize(@board_connection_at) : '-')) }
      = link_to "#last-connections", 'data-target' => '#last-connections', 'data-toggle' => 'modal' do
        = fa_icon 'fal fa-microchip opposite-color pr-1 bigger-2 vline-middle'
        %h5.m-0.opposite-color.vline-middle.inline-block.weight-2
          = I18n.t('menu.status')
        = connection_tag_for(@board_connection_at)
  %li.vline-middle
    = link_to signout_path do
      = fa_icon 'fal fa-power-off opposite-color pr-1 bigger-2 vline-middle'
      %h5.m-0.opposite-color.vline-middle.inline-block.weight-2
        = I18n.t('menu.sign_out')


= render partial: "shared/last_connections"