config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "users#welcome"

  get "users",            to: redirect("signup")
  get "signin",           to: "sessions#new"
  get "signout",          to: "sessions#destroy"
  get "signup",           to: "users#new"
  get "confirmation",     to: "users#confirmation"
  get "welcome",          to: "users#welcome"

  resources :users, only: %w(show new create update) do
    member do
      get "profile", to: "users#edit"
    end
  end

  resources :sessions, only: %w(new create destroy)
  resources :plantcares
  resources :waterings, only: %w(new create destroy index)
  resources :watering_schedules, except: %w(show)
  resources :board_connections, only: %w(index)
end

app/models/plantcare_api/plantcare.rb
# frozen_string_literal: true

# ERM plantcare model
require "her/file_upload"

module PlantcareApi
  class Plantcare < PlantcareApi::Base
    include Her::FileUpload

    WET_SENSOR_ARDUINO_FIELDS = {
      "SENSOR 1" => "A0",
      "SENSOR 2" => "A1",
      "SENSOR 3" => "A2",
      "SENSOR 4" => "A3",
      "SENSOR 5" => "A4",
      "SENSOR 6" => "A5"
    }.freeze

    KINDS = [
      SINGLE_KIND = "single",
      MULTIPLEX_KIND = "multiplex"
    ].freeze

    file_upload :attachments
    file_upload :picture

    attributes :name,
               :kind,
               :planted_at,
               :status,
               :wet,
               :wet_sensor_field,
               :watered_at,
               :wet_synced_at,
               :water_pump_field,
               :water_pump_id,
               :board_sleep_time,
               :board_watering_interval,
               :board_watering_interval_delay,
               :calibrate_board,
               :configure_board,
               :board_id

    has_one :board
    has_one :water_pump
    has_one :watering_schedule
    has_many :waterings

    delegate :auth_token,
             to: :board,
             prefix: true

    def wet
      super || 0.0
    end

    def status
      BigDecimal(wet.to_s) == BigDecimal("0.0") ? "non_data" : super
    end

    def single?
      kind == SINGLE_KIND
    end

    def multiplex?
      kind == MULTIPLEX_KIND
    end
  end
end

app/models/wtever_api/plantcare.rb
# frozen_string_literal: true

# ERM plantcare model
require "her/file_upload"

module WteverApi
  class Plantcare < WteverApi::Base
    include Her::FileUpload

    WET_SENSOR_ARDUINO_FIELDS = {
      "SENSOR 1" => "A0",
      "SENSOR 2" => "A1",
      "SENSOR 3" => "A2",
      "SENSOR 4" => "A3",
      "SENSOR 5" => "A4",
      "SENSOR 6" => "A5"
    }.freeze

    KINDS = [
      SINGLE_KIND = "single",
      MULTIPLEX_KIND = "multiplex"
    ].freeze

    file_upload :attachments
    file_upload :picture

    attributes :name,
               :kind,
               :planted_at,
               :status,
               :wet,
               :wet_sensor_field,
               :watered_at,
               :wet_synced_at,
               :water_pump_field,
               :water_pump_id,
               :board_sleep_time,
               :board_watering_interval,
               :board_watering_interval_delay,
               :calibrate_board,
               :configure_board

    has_one :board
    has_one :water_pump
    has_one :watering_schedule
    has_many :waterings

    delegate :auth_token,
             to: :board,
             prefix: true

    def wet
      super || 0.0
    end

    def status
      BigDecimal(wet.to_s) == BigDecimal("0.0") ? "non_data" : super
    end

    def single?
      kind == SINGLE_KIND
    end

    def multiplex?
      kind == MULTIPLEX_KIND
    end
  end
end

app/controllers/plantcares_controller.rb
# frozen_string_literal: true

class PlantcaresController < ApplicationController
  before_action :set_plantcare, only: %w(show edit)

  def index
    @plantcares = PlantcareApi::Plantcare.all
  end

  def show
  end

  def new
    @plantcare  = PlantcareApi::Plantcare.new
  end

  def create
    @plantcare  = PlantcareApi::Plantcare.new(plantcare_params)
    if @plantcare.save
      flash[:notice] = I18n.t("plantcares.create.sucessfully")

      redirect_to plantcares_path
    else
      flash[:error] = to_flash(@plantcare.response_errors)

      render "new"
    end
  end

  def edit
  end

  def update
    @plantcare = PlantcareApi::Plantcare.new(plantcare_params)

    if @plantcare.save
      flash[:notice] = I18n.t("plantcares.update.sucessfully")

      redirect_to plantcares_path
    else
      flash[:error] = to_flash(@plantcare.response_errors)

      render "edit"
    end
  end

  def destroy
    plantcare = PlantcareApi::Plantcare.find(params[:id])

    if plantcare.destroy
      flash[:notice] = I18n.t("plantcares.destroy.sucessfully")
    else
      flash[:error] = to_flash(@plantcare.response_errors)
    end

    redirect_to plantcares_path
  end

  private

  def plantcare_params
    params.require(:plantcare_api_plantcare).permit(
      :name,
      :picture,
      :attachments,
      :planted_at,
      :board_sleep_time,
      :board_watering_interval,
      :board_watering_interval_delay,
      :calibrate_board,
      :configure_board
    ).tap do |permitted_params|
      permitted_params[:id] = params[:id]
      permitted_params[:wet_sensor_field] = params.dig(:plantcare_api, :wet_sensor_field)
      permitted_params[:water_pump_field] = params.dig(:plantcare_api, :water_pump_field)
    end
  end

  def set_plantcare
    @plantcare = PlantcareApi::Plantcare.find(params[:id])
  end
end

app/helpers/plantcares_helper.rb
# frozen_string_literal: true

module PlantcaresHelper
  def plantcare_picture(plantcare)
    if plantcare.picture
      plantcare.picture
    else
      i = plantcare.id.to_i % 6 + 1
      image_url("plantcares/plantcare-default0#{i}.jpg")
    end
  end

  def plantcare_background(plantcare)
    if plantcare.picture
      "background-image: url('#{asset_path(plantcare.picture)}')"
    else
      i = plantcare.id.to_i % 6 + 1
      "background-image: url('#{image_url("plantcares/plantcare-default0#{i}.jpg")}')"
    end
  end

  def plantcare_wet(plantcare)
    number_to_percentage(plantcare.wet, strip_insignificant_zeros: true)
  end

  def boolean_collection
    [
      [I18n.t("form.boolean_collection.true_text"), true],
      [I18n.t("form.boolean_collection.false_text"), false]
    ]
  end

  def wet_sensors_collection
    PlantcareApi::PlantcareApi::WET_SENSOR_ARDUINO_FIELDS.to_a
  end

  def water_pumps_collection
    PlantcareApi::WaterPump::ARDUINO_FIELDS.to_a
  end

  def countries_collection
    PlantcareApi::Country.all.map { |country| [country.name.humanize, country.code] }
  end

  def timezones_collection
    ActiveSupport::TimeZone.all.map(&:name)
  end

  def lang_collection
    [
      ["🇪🇸", :es],
      ["🇬🇧", :en]
    ]
  end

  def last_connection_status_class(board_connection_at)
    return "connection-non-data" if board_connection_at.blank?

    healthy_check_offset = Time.current - DateTime.strptime(board_connection_at, "%d/%m/%y %H:%M")

    return "connection-less-than-5" if healthy_check_offset < 5.minutes
    return "connection-less-than-10" if healthy_check_offset < 10.minutes
    return "connection-less-than-15" if healthy_check_offset < 15.minutes

    "connection-less-than-20"
  end

  def last_connection_tag(board_connection_at)
    return "" if board_connection_at.blank?

    I18n.t("menu.status_explanation", board_connection_at: board_connection_at)
  end
end

app/views/plantcares/_card.haml
- if plantcare.multiplex?
  = render partial: "card_v1", locals: { plantcare: plantcare }
- else
  = render partial: "card_v2", locals: { plantcare: plantcare }

app/views/plantcares/_card_v1.haml
.plantcare-card.m-1{ data: { plantcare: plantcare.id } }
  .image-card
    = image_tag plantcare_picture(plantcare)
    .plantcare-info.text-center.p-2
      = link_to edit_plantcare_path(plantcare), class: "opposite-color text-uppercase goto-edit pb-1" do
        = I18n.t("plantcares.edit.goto-title")

      .pl-1
        .smaller-1.weight-2.opposite-color.text-left
          = I18n.t("plantcares.index.plantcare.wet_synced_at", wet_synced_at: plantcare.wet_synced_at || "-")
        = render partial: "detail", locals: { plantcare: plantcare, icon_classes: "fal fa-heartbeat", attribute: :wet, value: "#{plantcare.wet}%", custom_classes: "bigger-2", value_classes: plantcare.status }

      - if plantcare.planted_at
        .pl-3
          = render partial: "detail", locals: { plantcare: plantcare, icon_classes: "fal fa-hand-holding-seedling", attribute: :planted_at,  value: plantcare.planted_at }
      - if plantcare.watered_at
        .pl-3
          = render partial: "detail", locals: { plantcare: plantcare, icon_classes: "fal fa-hand-holding-water", attribute: :watered_at, value: plantcare.watered_at }

  .plantcare-body.p-2
    %h3.weight-2= plantcare.name
    - if plantcare.water_pump.present?
      = link_to new_watering_path(water_pump_id: plantcare.water_pump_id), remote: true, class: "font-color block mt-1 mb-0" do
        = fa_icon "fal fa-dewpoint vline-middle flex-inline"
        %h5.bigger-1.weight-2.vline-middle.m-0.flex-inline
          = I18n.t("waterings.new.title")

      - if plantcare.watering_schedule.present?
        = link_to edit_watering_schedule_path(id: plantcare.watering_schedule.id), remote: true, class: "font-color block mt-1 mb-0" do
          = fa_icon "far fa-calendar-alt vline-middle flex-inline"
          %h5.bigger-1.weight-2.vline-middle.m-0.flex-inline
            = I18n.t("watering_schedules.edit.title")
      - else
        = link_to new_watering_schedule_path(plantcare_id: plantcare.id), remote: true, class: "font-color block mt-1 mb-0" do
          = fa_icon "far fa-calendar-alt vline-middle flex-inline"
          %h5.bigger-1.weight-2.vline-middle.m-0.flex-inline
            = I18n.t("watering_schedules.new.title")

      %h6.text-uppercase.weight-3.mb-0.mt-4{ alt: I18n.t("plantcares.plantcare_api.attributes.watered_at") }
        = I18n.t("watering.next_title")
      - if plantcare.waterings.any?(&:programmed?)
        .mt-1
          = render partial: "waterings/info",
                   collection: plantcare.waterings.select(&:programmed?).last(3),
                   as: :watering
      - else
        = I18n.t("watering.no_pending_title").html_safe

    - else
      %h6.weight-2= I18n.t("waterpumps.edit.unconfigured")

:javascript
  $('[data-plantcare="#{plantcare.id}"]').change(function(){
    $(this).find('form').submit();
  });

app/views/plantcares/_card_v2.haml
.plantcare-card.m-1{ data: { plantcare: plantcare.id } }
  .image-card
    = image_tag plantcare_picture(plantcare)
    .plantcare-info.text-center.pl-2.pr-2
      - if plantcare.watering_schedule.present?
        .pb-2.text-right
          %span.label.label-inverse
            = I18n.t("plantcares.plantcare_api.watering_scheduler.status.active")
      .pl-1
        .smaller-1.weight-2.opposite-color.text-left
          = I18n.t("plantcares.index.plantcare.wet_synced_at", wet_synced_at: plantcare.wet_synced_at || "-")
        = render partial: "detail", locals: { plantcare: plantcare, icon_classes: "fal fa-heartbeat", attribute: :wet, value: "#{plantcare.wet}%", custom_classes: "bigger-2", value_classes: plantcare.status }

      .pl-3.pt-1.detail.text-left
        = svg_icon_tag("watering-icon", { classes: "icon pr-1 svg-opposite-color vline-bottom" })

        .inline-flex
          %h6.mb-1.mt-1.opposite-color.weight-2
            = I18n.t("plantcares.index.plantcare.watered_at")
          %h6.weight-2.opposite-color.m-0
            = plantcare.watered_at.presence || "-"

      - if plantcare.waterings.any?(&:programmed?)
        .pl-3.pt-1.detail.text-left
          = svg_icon_tag("watering-schedule-icon", { classes: "icon pr-1 svg-opposite-color vline-bottom" })

          .inline-flex
            %h6.mb-1.mt-1.opposite-color.weight-2
              = I18n.t("plantcares.index.plantcare.scheduled_watering_at")
            %h6.weight-2.opposite-color.m-0
              = plantcare.watered_at.presence || "-"
              = link_to waterings_path(board_id: plantcare.board_id), remote: true, class: "opposite-color inline-block weight-3" do
                = I18n.t("plantcares.index.plantcare.more_waterings")
      - elsif plantcare.waterings.any?
        .pl-3.pt-1.detail.text-left
          = svg_icon_tag("watering-schedule-icon", { classes: "icon pr-1 svg-opposite-color vline-bottom" })

          .inline-flex
            %h6.weight-2.opposite-color.m-0
              = link_to waterings_path(board_id: plantcare.board_id), remote: true, class: "opposite-color inline-block weight-3" do
                = I18n.t("plantcares.index.plantcare.all_waterings")

  .plantcare-body.p-2
    .text-right.mb-1
      = board_status_tag(plantcare.board.status)

    .detail.text-left.font-color
      = svg_icon_tag("board-icon", { classes: "icon pr-1 svg-font-color vline-bottom" })
      .inline-flex
        %h6.mb-1.mt-1.font-color.weight-2{ alt: I18n.t("plantcares.plantcare_api.attributes.last_connection_at") }
          = I18n.t("plantcares.index.plantcare.last_connection_at")
        %h6.weight-2.font-color.m-0
          = plantcare.board.last_connection_at.presence || "-"
          = link_to board_connections_path(board_id: plantcare.board_id), remote: true, class: "font-color inline-block weight-3" do
            = I18n.t("plantcares.index.plantcare.all_connections")

    %h2.weight-2= plantcare.name

    = link_to edit_plantcare_path(plantcare), class: "font-color block mt-1 mb-0" do
      = fa_icon "fal fa-pen-square vline-middle flex-inline"
      %h5.bigger-1.weight-2.vline-middle.m-0.flex-inline
        = I18n.t("plantcares.edit.goto-title")

    - if plantcare.water_pump.present?
      = link_to new_watering_path(water_pump_id: plantcare.water_pump_id), remote: true, class: "font-color block mt-1 mb-0" do
        = fa_icon "fal fa-dewpoint vline-middle flex-inline"
        %h5.bigger-1.weight-2.vline-middle.m-0.flex-inline
          = I18n.t("waterings.new.title")

      - if plantcare.watering_schedule.present?
        = link_to edit_watering_schedule_path(id: plantcare.watering_schedule.id), remote: true, class: "font-color block mt-1 mb-0" do
          = fa_icon "far fa-calendar-alt vline-middle flex-inline"
          %h5.bigger-1.weight-2.vline-middle.m-0.flex-inline
            = I18n.t("watering_schedules.edit.title")
      - else
        = link_to new_watering_schedule_path(plantcare_id: plantcare.id), remote: true, class: "font-color block mt-1 mb-0" do
          = fa_icon "far fa-calendar-alt vline-middle flex-inline"
          %h5.bigger-1.weight-2.vline-middle.m-0.flex-inline
            = I18n.t("watering_schedules.new.title")

    - else
      %h6.weight-2= I18n.t("waterpumps.edit.unconfigured")

:javascript
  $('[data-plantcare="#{plantcare.id}"]').change(function(){
    $(this).find('form').submit();
  });

app/views/plantcares/_common_details.haml
.flex.flex-direction-row.flex-justify-space-between.p-2

  .flex.flex-direction-column
    .pb-2= board_status_tag(plantcare.board.status)
    - if plantcare.wet
      = render partial: "detail", locals: { plantcare: plantcare, icon_classes: "fal fa-heartbeat", attribute: :wet, value: "#{plantcare.wet}%", value_classes: plantcare.status, custom_classes: "bigger-2" }

    .detail.text-left.opposite-color.pt-1
      = svg_icon_tag("watering-icon", { classes: "icon pr-1 svg-opposite-color vline-bottom" })

      .inline-flex.pl-1
        %h6.mb-1.mt-1.opposite-color.weight-2{ alt: I18n.t("plantcares.plantcare_api.attributes.watered_at") }
          = I18n.t("plantcares.index.plantcare.watered_at")
        %h6.weight-2.opposite-color.m-0
          = plantcare.watered_at.presence || "-"

    .detail.text-left.opposite-color.pt-1
      = svg_icon_tag("board-icon", { classes: "icon pr-1 svg-opposite-color vline-bottom" })
      .inline-flex.pl-1
        %h6.mb-1.mt-1.opposite-color.weight-2{ alt: I18n.t("plantcares.plantcare_api.attributes.last_connection_at") }
          = I18n.t("plantcares.index.plantcare.last_connection_at")
        %h6.weight-2.opposite-color.m-0
          = plantcare.board.last_connection_at.presence || "-"

  - if plantcare.id.present?
    .flex
      = link_to plantcare_path(plantcare), method: :delete, data: { confirm: I18n.t("confirmation") } do
        = fa_icon "fal fa-trash-alt bigger-2 pr-1 opposite-color vline-bottom"

app/views/plantcares/_detail.haml
- custom_classes ||= ""
- value_classes ||= ""
- icon_classes ||= ""
.flex{ class: "detail text-left #{custom_classes}" }
  = fa_icon "#{icon_classes} bigger-2 pr-1 opposite-color vline-bottom"

  .inline-flex
    %h5.mb-1.mt-1.opposite-color.weight-2{ alt: I18n.t("plantcares.plantcare_api.attributes.#{attribute}") }
      = I18n.t("plantcares.index.plantcare.#{attribute}")
    %h5.weight-2.bigger-1.opposite-color.m-0{ class: value_classes }
      = value

app/views/plantcares/_form.haml
= f.file_field :picture, class: "form-control hidden"
.row.plantcare-fields.pt-2
  .col-xs-12
    .flex.align-center
      = fa_icon 'fal fa-sliders-v-square first-color pr-2 bigger-2 vline-middle'
      %h3.m-0.vline-middle.weight-1
        = I18n.t("plantcares.form.configuration_title")
      %button{"class" => "custom-btn custom-btn-transparent", "aria-expanded" => "false", "data-target" => "#info", "data-toggle" => "collapse", "type" => "button", "style" => "margin-left: auto;" }
        = fa_icon "fal fa-info-square bigger-1 vline-middle"
    %h5.mt-1.third-color.weight-1
      = I18n.t("plantcares.form.configuration_text")

    #info.collapse
      - if @plantcare.multiplex?
        = render "multiplex_config_help"
      - if @plantcare.single?
        = render "single_config_help"

  - if @plantcare.multiplex?
    .col-xs-12.pt-4
      .well
        = label_for(f.object, :board_auth_token)
        %h5.m-0
          = I18n.t("plantcares.form.auth_token_text")
        %h4.weight-2.text-center
          = svg_icon_tag("board-icon", { classes: "icon pr-1 svg-general-color vline-middle" })
          .inline-block.vline-middle.weight-2
            = current_user.api_token

  - if @plantcare.single?
    .col-xs-12.pt-4
      .well
        = label_for(f.object, :board_auth_token)
        %h5.m-0
          = I18n.t("plantcares.form.auth_token_text")
        %h4.weight-2.text-center
          = svg_icon_tag("board-icon", { classes: "icon pr-1 svg-general-color vline-middle" })
          .inline-block.vline-middle.weight-2
            = @plantcare.board.auth_token

  .col-xs-12.col-sm-6
    .form-group
      = label_for(f.object, :name, class: "m-0")
      = f.text_field :name, class: "form-control"

  .col-xs-12.col-sm-6
    .form-group
      = label_for(f.object, :board_watering_interval, class: "m-0")
      = f.number_field :board_watering_interval, class: "form-control"

  .col-xs-12.col-sm-6
    .form-group
      = label_for(f.object, :board_watering_interval_delay, class: "m-0")
      = f.number_field :board_watering_interval_delay, class: "form-control"

  .col-xs-12.col-sm-6
    .form-group
      = label_for(f.object, :board_sleep_time, class: "m-0")
      = f.number_field :board_sleep_time, class: "form-control"

  .col-xs-12.col-sm-6
    .form-group
      = label_for(f.object, :calibrate_board, class: "m-0")
      = switch_for(f, :calibrate_board)

  .col-xs-12.col-sm-6
    .form-group
      = label_for(f.object, :configure_board, class: "m-0")
      = switch_for(f, :configure_board)

  - if @plantcare.multiplex?
    .col-xs-12.col-sm-6
      .form-group
        = label_for(f.object, :wet_sensor_field)
        = f.select :wet_sensor_field, wet_sensors_collection, { prompt: true }, { class: "form-control" }

    .col-xs-12.col-sm-6
      .form-group
        = label_for(f.object, :water_pump_field)
        = f.select :water_pump_field, water_pumps_collection, { prompt: true }, { class: "form-control" }

:javascript
  uploaderControl($("#edit-picture"), $("#plantcare-panel"), $("#plantcare_api_picture"));

app/views/plantcares/_instructions.haml
.hidden-xs
  .flex.align-center.pt-4.pb-4
    = image_tag "instructions/step-one.png", width: 500, class: "pr-4"
    .flex.flex-direction-column.text-align-justify.instruction-step
      %h4.weight-3.mt-2= I18n.t("plantcares.index.instructions.step-1.title")
      %h5.weight-2= I18n.t("plantcares.index.instructions.step-1.description", link: link_to(I18n.t("plantcares.new.here"), new_plantcare_path, class: "general-color")).html_safe

  .flex.align-center.pt-4.pb-4
    .flex.flex-direction-column.text-align-justify.instruction-step
      %h4.weight-3.mt-2= I18n.t("plantcares.index.instructions.step-2.title")
      %h5.weight-2= I18n.t("plantcares.index.instructions.step-2.description").html_safe
    = image_tag "instructions/step-two.png", width: 500, class: "pl-4"

  .flex.align-center.pt-4.pb-4
    = image_tag "instructions/step-three.png", width: 500, class: "pr-4"
    .flex.flex-direction-column.text-align-justify.instruction-step
      %h4.weight-3.mt-2= I18n.t("plantcares.index.instructions.step-3.title")
      %h5.weight-2= I18n.t("plantcares.index.instructions.step-3.description").html_safe

  .flex.align-center.pt-4.pb-4
    .flex.flex-direction-column.text-align-justify.instruction-step
      %h4.weight-3.mt-2= I18n.t("plantcares.index.instructions.step-4.title")
      %h5.weight-2= I18n.t("plantcares.index.instructions.step-4.description").html_safe
      = link_to I18n.t("plantcares.index.get-back-garden"), '#the-garden', class: "ref custom-btn custom-btn-secondary"
    = image_tag "instructions/step-four.png", width: 500, class: "pl-4"


.visible-xs.p-2
  .flex.flex-direction-column.align-center.pt-4.pb-4
    = image_tag "instructions/step-one.png", width: 350
    .flex.flex-direction-column.text-align-justify.instruction-step
      %h4.weight-3.mt-2= I18n.t("plantcares.index.instructions.step-1.title")
      %h5.weight-2= I18n.t("plantcares.index.instructions.step-1.description", link: link_to(I18n.t("plantcares.new.here"), new_plantcare_path, class: "general-color weight-2")).html_safe

  .flex.flex-direction-column.align-center.pt-4.pb-4
    = image_tag "instructions/step-two.png", width: 350
    .flex.flex-direction-column.text-align-justify.instruction-step
      %h4.weight-3.mt-2= I18n.t("plantcares.index.instructions.step-2.title")
      %h5.weight-2= I18n.t("plantcares.index.instructions.step-2.description").html_safe

  .flex.flex-direction-column.align-center.pt-4.pb-4
    = image_tag "instructions/step-three.png", width: 350
    .flex.flex-direction-column.text-align-justify.instruction-step
      %h4.weight-3.mt-2= I18n.t("plantcares.index.instructions.step-3.title")
      %h5.weight-2= I18n.t("plantcares.index.instructions.step-3.description").html_safe

  .flex.flex-direction-column.align-center.pt-4.pb-4
    = image_tag "instructions/step-four.png", width: 350
    .flex.flex-direction-column.text-align-justify.instruction-step
      %h4.weight-3.mt-2= I18n.t("plantcares.index.instructions.step-4.title")
      %h5.weight-2= I18n.t("plantcares.index.instructions.step-4.description").html_safe
      = link_to I18n.t("plantcares.index.get-back-garden"), '#the-garden', class: "ref custom-btn custom-btn-secondary"

app/views/plantcares/edit.haml
#plantcare-panel.plantcare.opposite-color.p-2.vline-top{style: plantcare_background(@plantcare)}
  .row
    .col-xs-12.col-sm-8.col-sm-offset-2.col-md-6.col-md-offset-3
      = render partial: "plantcares/common_details",
                locals: { plantcare: @plantcare, show_watering: false }

  .title.text-center
    %h4#edit-picture.m-0.p-1
      = fa_icon "fal fa-camera-retro opposite-color"
.row{"style" => "width: 100%"}
  .col-xs-12.col-sm-8.col-sm-offset-2.col-md-6.col-md-offset-3
    .p-2
      = form_for @plantcare, url: plantcare_path(@plantcare), method: :put, html: { id: "form_plantcare_api" } do |f|
        = render partial: "form", locals: { f: f, form_id: "form_plantcare_api" }

        .pt-2
          = render "shared/form/submit", f: f

app/views/plantcares/index.haml
- if @plantcares.present?
  .vline-middle.the-garden.flex.flex-direction-column.flex-justify-center.align-center.bg-one-color#the-garden
    = render partial: "shared/title", locals: { title: I18n.t("plantcares.index.title"), subtitle: I18n.t("plantcares.index.subtitle") }

    .text-center.mt-3.mb-3.new-plantcare
      = link_to I18n.t("plantcares.new.title"), new_plantcare_path, class: "custom-btn custom-btn-secondary"
      = link_to I18n.t("plantcares.index.how-it-works"), '#instructions', class: "ref custom-btn custom-btn-secondary"

    .plantcare-cards.pt-3.pb-4
      = render partial: "card", collection: @plantcares, as: :plantcare

  #new_watering_modal
  #edit_watering_modal
  #waterings_modal
  #new_watering_schedule_modal
  #edit_watering_schedule_modal
  #board_connections_modal

- else
  .intro.p-1.content.vline-middle.bg-one-color
    = render partial: "shared/title", locals: { title: I18n.t("plantcares.index.title"), subtitle: I18n.t("plantcares.index.subtitle") }

    .mt-4
      .row
        .col-xs-12.col-sm-8.col-sm-offset-2.col-md-6.col-md-offset-3
          .text-center.pt-3
            = link_to I18n.t("plantcares.new.title"), new_plantcare_path, class: "custom-btn custom-btn-secondary"
            = link_to I18n.t("plantcares.index.how-it-works"), '#instructions', class: "ref custom-btn custom-btn-secondary"

.vline-middle.the-instructions.flex.flex-direction-column.flex-justify-center.align-center.pb-4.bg-two-color{id:"instructions"}
  = render partial: "shared/title", locals: { title: I18n.t("plantcares.index.instructions.title"), subtitle: I18n.t("plantcares.index.instructions.subtitle") }
  %section.mt-4.pt-3.pl-1.pr-1
    .row
      .col-xs-12.col-lg-8.col-lg-offset-2.col-xl-6.col-xl-offset-3
        = render partial: "instructions"

:javascript
  $(document).ready(function(){
    $(".action").each(function(){
      $(this).addClass("swashIn");
    });
  })